### ISSUE TITLE
not compiling for ePaper ESP8266

### ISSUE THREAD

**Issue by KHome** [chrismilleruk/mos-lib-epd2in9b#1]
Action done: "Rebuild app firmware" - leads to issue:
/fwbuild-volumes/2.5.1/apps/mos-lib-epd2in9b-master/esp8266/build_contexts/build_ctx_703492663/src/epdif.cpp:60:6: error: unused parameter 'arg' [-Werror=unused-parameter]
 void handle_busy_int(int pin, void *arg) {

What went wrong?

I've got this board:https://www.waveshare.com/wiki/E-Paper_ESP8266_Driver_Board

**Comment by chrismilleruk** [comment]
Looks like the ESP8266 build options treat warnings as errors. 

Fixed by resolving the warnings in cd3e2c7c8643d7923cf0b5a4018917bf623413ab

**Comment by chrismilleruk** [comment]
@KHome can you confirm this resolves your issue?

**Comment by KHome** [comment]
Issue solved. Compiling for 8266 works. Thank you!

**Comment by KHome** [comment]
Issue solved. Compiling for 8266 works. Thank you!
